[programs.localnet]
solana_twitter = "7wcobSpj8qrNtHycFaop7BxEWzbf81SRQUd8rsc6kNS5"

[programs.devnet]
solana_twitter = "7wcobSpj8qrNtHycFaop7BxEWzbf81SRQUd8rsc6kNS5"

[programs.mainnet]
solana_twitter = "7wcobSpj8qrNtHycFaop7BxEWzbf81SRQUd8rsc6kNS5"

[registry]
url = "https://anchor.projectserum.com"

# Specifies a custom Directory that the IDL File should be copied to every Time `anchor build` is run
[workspace]
types = "app/src/idl/"

# The File `target/deploy/solana_twitter-keypair.json` is important to acknowledge that this File is the Proof that some is owning the Program at this Address
# Everyone who holds the Keypair will be able to deploy any Ahanges they want to these Solana Program
# Anchor generate a Provider Object that uses the following Configurations
[provider]
cluster = "devnet"
wallet = "/home/michael/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"